### ISSUE TITLE
cc-block icon alt is inverted

### ISSUE THREAD

**Issue by miton18** [CleverCloud/clever-components#759] opened 2023-05-30 17:15 UTC
Trying to use the cc-block component with an icon:

https://www.clever-cloud.com/doc/clever-components/?path=/docs/%F0%9F%A7%AC-molecules-cc-block--state-with-open

When the cursor is hover the icon, the displayed text 'open' 'close' is inverted

**Comment by pdesoyres-cc** [comment] 2023-05-30 17:29
Duplicate of #752

**Closed** 2023-06-05 08:10 UTC
Labels: duplicate
